# -*- coding: utf-8 -*-
"""neural.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGyFo43FFFY1JobfORUATZ-jtkOpYyhM
"""

import torch
import torch.nn as nn

model =nn.Sequential(
  nn.Linear(2, 4),
  nn.ReLU(),
  nn.Linear(4, 1),
)